<?php

namespace MaisonLigues\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiaisonRepository extends EntityRepository
{
}
