<?php

namespace MaisonLigues\CroisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TraverseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraverseeRepository extends EntityRepository
{
}
